# Generated by Django 3.0.2 on 2020-01-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='from_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.Channel'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='to_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='playlistentry',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Video'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='streamer.PlaylistEntry'),
        ),
        migrations.AddField(
            model_name='likes',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='likes',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Video'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Channel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='streamer.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Video'),
        ),
    ]
